/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 keycap.gltf 
Author: snacksthecat (https://sketchfab.com/snacksthecat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/micro-switch-sd-keycap-2fc5209b25984e6f82f5e882c31e61ca
Title: Micro Switch SD Keycap
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/keycap.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, -0.226, Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material1_0.geometry} material={materials.material1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/keycap.gltf')
